---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# fquantdr

<!-- badges: start -->
<!-- badges: end -->

## Overview

fquantdr is a package that takes discrete numerical inputs, transform the data into functional data, and use dimension reduction to reduce the observations, after which we will apply quantile regression.


## Installation


<!-- You can install the development version of fquantdr from --> <!-- [GitHub](https://github.com/fquantdr) with: -->

``` r
# To install the package 
install.packages("fquantdr")

# To install development version from Github
# install.packages("devtools")
devtools::install_github("elianachristou/fquantdr")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(fquantdr)
## basic example code
```


<!-- You'll still need to render `README.Rmd` regularly, to keep `README.md` up-to-date. `devtools::build_readme()` is handy for this.

You can also embed plots, for example:

```{r pressure, echo = FALSE}
plot(pressure)
```

In that case, don't forget to commit and push the resulting figure files, so they display on GitHub and CRAN. -->

## Usage

<!-- Include ADHD applications? -->

